

version: '3.8'

services:

  db:
    container_name: "alco_test_db"
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 3

  # app:
  #   container_name: "alco_app"
  #   build: .
  #   entrypoint: ["sh", "-c", "(cd db && alembic upgrade head) && uvicorn api.main:app --host 0.0.0.0 --reload"]
  #   # entrypoint: ["sh", "-c", "(cd db && alembic upgrade head)"]
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   ports:
  #       - "8000:8000"
